import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { tanstackRouter } from '@tanstack/router-plugin/vite';
import path from 'path';
import tailwindcss from '@tailwindcss/vite';
import os from 'os';
import fs from 'fs';

function getLocalIP() {
  const interfaces = os.networkInterfaces();

  for (const name of Object.keys(interfaces)) {
    for (const net of interfaces[name] || []) {
      if (
        net.family === 'IPv4' &&
        !net.internal
      ) {
        return net.address;
      }
    }
  }

  return 'localhost';
}

const ip = getLocalIP();

// Load self-signed certificates generated by generate-certs.ts
const certsDir = path.resolve(__dirname, '../certs');
const httpsConfig = fs.existsSync(path.join(certsDir, 'server-key.pem'))
  ? {
      key: fs.readFileSync(path.join(certsDir, 'server-key.pem')),
      cert: fs.readFileSync(path.join(certsDir, 'server.pem')),
    }
  : undefined; // Fallback to HTTP if certs not yet generated

// https://vite.dev/config/
export default defineConfig({
  server: {
    host: true,
    https: httpsConfig,
    proxy: {
      '/api': {
        target: `https://${ip}:3000`,
        secure: false, // Accept self-signed certs
      },
      '/ws': {
        target: `wss://${ip}:3000`,
        ws: true,
        secure: false, // Accept self-signed certs
      },
    },
  },
  plugins: [
    tanstackRouter({
      target: 'react',
      autoCodeSplitting: true,
    }),
    react({
      babel: {
        plugins: [['babel-plugin-react-compiler']],
      },
    }),
    tailwindcss(),
  ],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
});
