/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as User_pageRouteImport } from './routes/user_page'
import { Route as LoginRouteImport } from './routes/login'
import { Route as Admin_pageRouteImport } from './routes/admin_page'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminAddUserRouteImport } from './routes/admin/add-user'
import { Route as AdminView_and_remove_usersPageRouteImport } from './routes/admin/view_and_remove_users/page'

const User_pageRoute = User_pageRouteImport.update({
  id: '/user_page',
  path: '/user_page',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Admin_pageRoute = Admin_pageRouteImport.update({
  id: '/admin_page',
  path: '/admin_page',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAddUserRoute = AdminAddUserRouteImport.update({
  id: '/admin/add-user',
  path: '/admin/add-user',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminView_and_remove_usersPageRoute =
  AdminView_and_remove_usersPageRouteImport.update({
    id: '/admin/view_and_remove_users/page',
    path: '/admin/view_and_remove_users/page',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin_page': typeof Admin_pageRoute
  '/login': typeof LoginRoute
  '/user_page': typeof User_pageRoute
  '/admin/add-user': typeof AdminAddUserRoute
  '/admin/view_and_remove_users/page': typeof AdminView_and_remove_usersPageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin_page': typeof Admin_pageRoute
  '/login': typeof LoginRoute
  '/user_page': typeof User_pageRoute
  '/admin/add-user': typeof AdminAddUserRoute
  '/admin/view_and_remove_users/page': typeof AdminView_and_remove_usersPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin_page': typeof Admin_pageRoute
  '/login': typeof LoginRoute
  '/user_page': typeof User_pageRoute
  '/admin/add-user': typeof AdminAddUserRoute
  '/admin/view_and_remove_users/page': typeof AdminView_and_remove_usersPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin_page'
    | '/login'
    | '/user_page'
    | '/admin/add-user'
    | '/admin/view_and_remove_users/page'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin_page'
    | '/login'
    | '/user_page'
    | '/admin/add-user'
    | '/admin/view_and_remove_users/page'
  id:
    | '__root__'
    | '/'
    | '/admin_page'
    | '/login'
    | '/user_page'
    | '/admin/add-user'
    | '/admin/view_and_remove_users/page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Admin_pageRoute: typeof Admin_pageRoute
  LoginRoute: typeof LoginRoute
  User_pageRoute: typeof User_pageRoute
  AdminAddUserRoute: typeof AdminAddUserRoute
  AdminView_and_remove_usersPageRoute: typeof AdminView_and_remove_usersPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user_page': {
      id: '/user_page'
      path: '/user_page'
      fullPath: '/user_page'
      preLoaderRoute: typeof User_pageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_page': {
      id: '/admin_page'
      path: '/admin_page'
      fullPath: '/admin_page'
      preLoaderRoute: typeof Admin_pageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/add-user': {
      id: '/admin/add-user'
      path: '/admin/add-user'
      fullPath: '/admin/add-user'
      preLoaderRoute: typeof AdminAddUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/view_and_remove_users/page': {
      id: '/admin/view_and_remove_users/page'
      path: '/admin/view_and_remove_users/page'
      fullPath: '/admin/view_and_remove_users/page'
      preLoaderRoute: typeof AdminView_and_remove_usersPageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Admin_pageRoute: Admin_pageRoute,
  LoginRoute: LoginRoute,
  User_pageRoute: User_pageRoute,
  AdminAddUserRoute: AdminAddUserRoute,
  AdminView_and_remove_usersPageRoute: AdminView_and_remove_usersPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
