/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserUser_pageRouteImport } from './routes/user/user_page'
import { Route as UserSelectedConversationIdRouteImport } from './routes/user/$selectedConversationId'
import { Route as AdminAdmin_pageRouteImport } from './routes/admin/admin_page'
import { Route as AdminAdd_userRouteImport } from './routes/admin/add_user'
import { Route as AdminView_and_remove_usersPageRouteImport } from './routes/admin/view_and_remove_users/page'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUser_pageRoute = UserUser_pageRouteImport.update({
  id: '/user/user_page',
  path: '/user/user_page',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSelectedConversationIdRoute =
  UserSelectedConversationIdRouteImport.update({
    id: '/user/$selectedConversationId',
    path: '/user/$selectedConversationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAdmin_pageRoute = AdminAdmin_pageRouteImport.update({
  id: '/admin/admin_page',
  path: '/admin/admin_page',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdd_userRoute = AdminAdd_userRouteImport.update({
  id: '/admin/add_user',
  path: '/admin/add_user',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminView_and_remove_usersPageRoute =
  AdminView_and_remove_usersPageRouteImport.update({
    id: '/admin/view_and_remove_users/page',
    path: '/admin/view_and_remove_users/page',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/add_user': typeof AdminAdd_userRoute
  '/admin/admin_page': typeof AdminAdmin_pageRoute
  '/user/$selectedConversationId': typeof UserSelectedConversationIdRoute
  '/user/user_page': typeof UserUser_pageRoute
  '/admin/view_and_remove_users/page': typeof AdminView_and_remove_usersPageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/add_user': typeof AdminAdd_userRoute
  '/admin/admin_page': typeof AdminAdmin_pageRoute
  '/user/$selectedConversationId': typeof UserSelectedConversationIdRoute
  '/user/user_page': typeof UserUser_pageRoute
  '/admin/view_and_remove_users/page': typeof AdminView_and_remove_usersPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/add_user': typeof AdminAdd_userRoute
  '/admin/admin_page': typeof AdminAdmin_pageRoute
  '/user/$selectedConversationId': typeof UserSelectedConversationIdRoute
  '/user/user_page': typeof UserUser_pageRoute
  '/admin/view_and_remove_users/page': typeof AdminView_and_remove_usersPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/add_user'
    | '/admin/admin_page'
    | '/user/$selectedConversationId'
    | '/user/user_page'
    | '/admin/view_and_remove_users/page'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/add_user'
    | '/admin/admin_page'
    | '/user/$selectedConversationId'
    | '/user/user_page'
    | '/admin/view_and_remove_users/page'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/add_user'
    | '/admin/admin_page'
    | '/user/$selectedConversationId'
    | '/user/user_page'
    | '/admin/view_and_remove_users/page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminAdd_userRoute: typeof AdminAdd_userRoute
  AdminAdmin_pageRoute: typeof AdminAdmin_pageRoute
  UserSelectedConversationIdRoute: typeof UserSelectedConversationIdRoute
  UserUser_pageRoute: typeof UserUser_pageRoute
  AdminView_and_remove_usersPageRoute: typeof AdminView_and_remove_usersPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/user_page': {
      id: '/user/user_page'
      path: '/user/user_page'
      fullPath: '/user/user_page'
      preLoaderRoute: typeof UserUser_pageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$selectedConversationId': {
      id: '/user/$selectedConversationId'
      path: '/user/$selectedConversationId'
      fullPath: '/user/$selectedConversationId'
      preLoaderRoute: typeof UserSelectedConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/admin_page': {
      id: '/admin/admin_page'
      path: '/admin/admin_page'
      fullPath: '/admin/admin_page'
      preLoaderRoute: typeof AdminAdmin_pageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/add_user': {
      id: '/admin/add_user'
      path: '/admin/add_user'
      fullPath: '/admin/add_user'
      preLoaderRoute: typeof AdminAdd_userRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/view_and_remove_users/page': {
      id: '/admin/view_and_remove_users/page'
      path: '/admin/view_and_remove_users/page'
      fullPath: '/admin/view_and_remove_users/page'
      preLoaderRoute: typeof AdminView_and_remove_usersPageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminAdd_userRoute: AdminAdd_userRoute,
  AdminAdmin_pageRoute: AdminAdmin_pageRoute,
  UserSelectedConversationIdRoute: UserSelectedConversationIdRoute,
  UserUser_pageRoute: UserUser_pageRoute,
  AdminView_and_remove_usersPageRoute: AdminView_and_remove_usersPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
